name: try_fit
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
#  https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1
  #  https://pub.dev/packages/get
  get: ^4.6.6
    #  https://pub.dev/packages/flutter_easyloading/versions
  flutter_easyloading: ^3.0.5
    #  https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3
    #  https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
    #  https://pub.dev/packages/dio
  dio: ^5.5.0+1
    #  https://pub.dev/packages/image_picker
  image_picker: ^1.1.2
    #  https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1

  flutter_staggered_grid_view: ^0.7.0
#https://pub.dev/packages/firebase_core
  firebase_core: ^3.2.0
#https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^5.1.0
#https://pub.dev/packages/firebase_storage
  firebase_storage: ^12.1.1
#https://pub.dev/packages/image_picker
image_picker: ^1.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/

